### ISSUE TITLE
Add repository metadata to Makefile

### ISSUE THREAD

**Issue by oalders** [CaballerosTeam/Sort-Naturally-XS#1]
This would make the repository easy to find from MetaCPAN.  Please see https://perlmaven.com/how-to-add-link-to-version-control-system-of-a-cpan-distributions

**Comment by CaballerosTeam** [comment]
@oalders, done [6f83642d](https://github.com/CaballerosTeam/Sort-Naturally-XS/commit/6f83642d0dfd17e5a719db6a1f43184ba9ba0353)

**Comment by oalders** [comment]
Thanks @CaballerosTeam!
